POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer OjE3MDg0MjIwMzF9.XW022nhLH_1BIyFAVC8mJRpsUwMeItXZIPRyAv0UioM

{
  "title": "Hello",
  "author": "Putin",
  "url": "blogUrlTest",
  "likes": 23
}